// Constants for game parameters
window.ATTACK_RANGE = 5;
window.ATTACK_CONE_ANGLE = Math.PI / 3; // 60 degrees
window.COMBO_WINDOW = 1; // Max time in seconds between attacks to continue combo
window.OBJECT2_MAX_HEALTH = 1000;
window.AI_UPDATE_PER_FRAME = 1; // Number of enemies to update per frame for AI scheduling
window.PLAYER_SPEED = 10; // Player movement speed
window.ENEMY_SPEED = 7.0; // Enemy movement speed
window.PLAYER_MAX_HEALTH = 100; // Max player health
window.BARRICADE_HEALTH = 100; // Initial barricade health
window.BARRICADE_ATTACK_DAMAGE = 35; // Damage dealt to barricades by enemies
window.ENEMY_ATTACK_DAMAGE = 10; // Damage dealt to player by enemies
window.OBJECT2_ATTACK_DAMAGE = 25; // Damage dealt to Object_2 by enemies
window.HEALTH_PICKUP_AMOUNT = 25; // Amount of health restored by pickup
window.MONEY_PER_KILL = 10; // Money gained per enemy kill
window.PLAYER_HEIGHT = 1.6; // Player character height for collision
window.PLAYER_RADIUS = 0.4; // Player character radius for collision
window.GRAVITY = 9.8; // Gravity value
window.GROUND_LIMIT_Y = 5.00; // Y-coordinate limit for falling
window.SKELETON_DEFAULT_Y = 5.50; // Default Y position for skeletons
window.PLAYER_SPAWN_Y_OFFSET = 50; // Y-offset for player spawn raycast
window.PICKUP_PROMPT_OFFSET_Y = 2; // Y-offset for pickup prompt above item
window.PICKUP_COLLECTION_RANGE = 3; // Distance within which player can collect pickups
window.ENEMY_AGGRO_RADIUS = 15; // Distance within which enemy will aggro player
window.ENEMY_ATTACK_RANGE = 5; // Distance within which enemy will attack target
window.ENEMY_BARRICADE_CHECK_RANGE = 5; // Distance for enemy to check for barricades
